# Generated by Django 6.1.1 on 2026-10-06 12:34

import common.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="baseuser",
            options={
                "ordering": ["full_name"],
                "verbose_name": "Utilisateur",
                "verbose_name_plural": "Utilisateurs",
            },
        ),
        migrations.AlterModelOptions(
            name="member",
            options={
                "ordering": ["user__full_name"],
                "verbose_name": "Membre",
                "verbose_name_plural": "Membres",
            },
        ),
        migrations.AlterModelOptions(
            name="rabbin",
            options={
                "ordering": ["user__full_name"],
                "verbose_name": "Rabbin",
                "verbose_name_plural": "Rabbins",
            },
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="address",
            field=models.CharField(blank=True, max_length=200, verbose_name="Adresse"),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="phone",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This number phone is not allowed.",
                        regex="^(01|05|07)\\d{8}$",
                    )
                ],
                verbose_name="Téléphone",
            ),
        ),
        migrations.AlterField(
            model_name="baseuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Super-utilisateur"),
                    ("RABBIN", "Rabbin"),
                    ("MEMBER", "Membre"),
                ],
                db_index=True,
                default="MEMBER",
                max_length=10,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="matricule",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Matricule",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="rabbin",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/rabbins/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "webp"],
                        message="Extension non autorisée. Seuls les formats PNG et WEBP sont acceptés.",
                    ),
                    common.validators.validate_file_size,
                ],
                verbose_name="Photo de profil",
            ),
        ),
        migrations.AlterField(
            model_name="rabbin",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rabbin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AddIndex(
            model_name="baseuser",
            index=models.Index(
                fields=["full_name"], name="accounts_ba_full_na_f2d470_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="baseuser",
            index=models.Index(fields=["role"], name="accounts_ba_role_75aa12_idx"),
        ),
        migrations.AddIndex(
            model_name="baseuser",
            index=models.Index(
                fields=["is_active"], name="accounts_ba_is_acti_399495_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(
                fields=["matricule"], name="accounts_me_matricu_9a3174_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="member",
            index=models.Index(fields=["user"], name="accounts_me_user_id_7cf4b8_idx"),
        ),
        migrations.AddIndex(
            model_name="rabbin",
            index=models.Index(fields=["user"], name="accounts_ra_user_id_630937_idx"),
        ),
    ]
