# Generated by Django 6.1.1 on 2026-10-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_baseuser_options_alter_member_options_and_more"),
        ("core", "0002_blogpost_is_published_event_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="temple",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="core.temple",
                verbose_name="Communauté / Temple",
            ),
        ),
    ]
