# Generated by Django 6.1.1 on 2026-10-06 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_alter_baseuser_options_alter_member_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog catégorie",
                "verbose_name_plural": "Blogs catégories",
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=200,
                        unique=True,
                        verbose_name="Event category name",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Temple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Nom du temple"
                    ),
                ),
                ("address", models.CharField(max_length=200, verbose_name="Adresse")),
                (
                    "rabbin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="temple",
                        to="accounts.rabbin",
                        verbose_name="Rabbin",
                    ),
                ),
            ],
            options={
                "verbose_name": "Temple",
                "verbose_name_plural": "Temples",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MemberRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "adherent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Demandeur",
                    ),
                ),
                (
                    "temple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_requests",
                        to="core.temple",
                        verbose_name="Temple",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'adhésion",
                "verbose_name_plural": "Demandes d'adhésion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(blank=True, verbose_name="Description")),
                ("date", models.DateTimeField(verbose_name="Date et heure")),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.eventtype",
                    ),
                ),
                (
                    "temple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="core.temple",
                        verbose_name="Temple",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement",
                "verbose_name_plural": "Événements",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("title", models.CharField(max_length=200, verbose_name="Titre")),
                ("content", models.TextField(blank=True, verbose_name="Contenu")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_post",
                        to="core.blogcategory",
                    ),
                ),
                (
                    "temple",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to="core.temple",
                        verbose_name="Temple",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article de blog",
                "verbose_name_plural": "Articles de blog",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationLetter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user__role": "RABBIN"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_recommendation_letters",
                        to="accounts.rabbin",
                        verbose_name="Approuvée par",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_letters",
                        to="accounts.member",
                        verbose_name="Membre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettre de recommandation",
                "verbose_name_plural": "Lettres de recommandation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["member"], name="core_recomm_member__027048_idx"
                    ),
                    models.Index(
                        fields=["approved_by"], name="core_recomm_approve_14baf4_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="temple",
            index=models.Index(fields=["name"], name="core_temple_name_da74cf_idx"),
        ),
        migrations.AddIndex(
            model_name="temple",
            index=models.Index(
                fields=["rabbin"], name="core_temple_rabbin__8b4b0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberrequest",
            index=models.Index(
                fields=["adherent"], name="core_member_adheren_803492_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberrequest",
            index=models.Index(
                fields=["temple"], name="core_member_temple__bb435d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memberrequest",
            index=models.Index(
                fields=["temple", "adherent"], name="core_member_temple__23b382_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="memberrequest",
            constraint=models.UniqueConstraint(
                fields=("adherent", "temple"), name="unique_member_request_per_temple"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="core_event_date_058a3e_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["temple", "date"], name="core_event_temple__45e0ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["title"], name="core_event_title_ad75b8_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["title"], name="core_blogpo_title_876e8b_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["temple"], name="core_blogpo_temple__bd984c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["temple", "created_at"], name="core_blogpo_temple__b2ed4e_idx"
            ),
        ),
    ]
