# Generated by Django 6.1.1 on 2026-10-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="memberrequest",
            name="guest_address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="memberrequest",
            name="guest_full_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Nom complet"
            ),
        ),
        migrations.AddField(
            model_name="memberrequest",
            name="guest_phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Téléphone"),
        ),
    ]
