# Generated by Django 6.1.2 on 2026-10-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_is_published_event_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'ordering': ['name'], 'verbose_name': "Type d'evenement", 'verbose_name_plural': "Types d'evenements"},
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True, verbose_name="Catégorie d'un évènement"),
        ),
    ]
